# https://taskfile.dev
version: "3"

tasks:
  create-venv:
    status:
      - test -f .venv/bin/pip
    cmds:
      - python3 -m venv .venv
  install-maturin:
    status:
      - which .venv/bin/maturin
    cmds:
      - task: create-venv
      - .venv/bin/pip install 'maturin[patchelf]'
  install:
    sources:
      - pyproject.toml
      - Cargo.toml
      - Cargo.lock
    status:
      - test -f .venv/lib/*/site-packages/firefly_test.pth
    cmds:
      - task: install-maturin
      - .venv/bin/maturin develop --extras test,lint
  format:
    cmds:
      - task: install
      - cargo fmt
      - .venv/bin/ruff check --fix-only .
  lint:
    cmds:
      - task: install
      - cargo clippy
      - .venv/bin/ruff check .
      - .venv/bin/mypy
  test:
    cmds:
      - task: install
      - cargo test
      - .venv/bin/pytest {{.CLI_ARGS}}
  all:
    cmds:
      - task: format
      - task: lint
      - task: test
